-- Uruchom w Supabase: SQL Editor -> New query -> wklej i Run.
-- Tabela pamieta historie wpisanych faktur - W PRZECIWIENSTWIE do oznaczone_prawidlowe
-- (schema.sql, wspoldzielona miedzy wszystkimi zalogowanymi), ta jest PER KONTO: RLS ogranicza
-- kazdemu userowi widocznosc/zapis/usuwanie wylacznie do wlasnych wierszy.

create table if not exists historia_faktur (
    id bigint generated by default as identity primary key,
    user_id uuid not null references auth.users(id) default auth.uid(),
    nazwa_pliku text not null,
    wpisano_dnia timestamptz not null default now(),
    nierozpoznana boolean not null,
    powod_odrzucenia text,
    pozycje jsonb not null
);

alter table historia_faktur enable row level security;

create policy "user czyta wlasna historie" on historia_faktur
    for select using (auth.uid() = user_id);

create policy "user dodaje do wlasnej historii" on historia_faktur
    for insert with check (auth.uid() = user_id);

create policy "user usuwa z wlasnej historii" on historia_faktur
    for delete using (auth.uid() = user_id);
